export const perfumes = [
  {
    id: "1",
    name: "Midnight Elegance",
    brand: "Luxe Fragrances",
    price: 89.99,
    image: "/luxury-perfume-bottle-midnight-elegance.jpg",
    description: "A sophisticated blend of dark florals and woody notes",
    notes: ["Bergamot", "Jasmine", "Sandalwood"],
    volume: "100ml",
    rating: 4.8,
    stock: 25,
  },
  {
    id: "2",
    name: "Summer Breeze",
    brand: "Fresh Scents",
    price: 65.99,
    image: "/light-fresh-perfume-bottle-summer.jpg",
    description: "Light and refreshing citrus fragrance perfect for warm days",
    notes: ["Lemon", "Coconut", "Musk"],
    volume: "75ml",
    rating: 4.6,
    stock: 15,
  },
  {
    id: "3",
    name: "Rose Garden",
    brand: "Botanical Bliss",
    price: 75.99,
    image: "/rose-perfume-bottle-floral.jpg",
    description: "Romantic rose fragrance with hints of vanilla",
    notes: ["Rose", "Peony", "Vanilla"],
    volume: "100ml",
    rating: 4.7,
     stock: 52,
  },
  {
    id: "4",
    name: "Ocean Mist",
    brand: "Aquatic Dreams",
    price: 72.99,
    image: "/aquatic-perfume-bottle-ocean.jpg",
    description: "Fresh aquatic scent with marine and mineral notes",
    notes: ["Sea Salt", "Ambroxan", "Driftwood"],
    volume: "100ml",
    rating: 4.5,
     stock: 45,
  },
  {
    id: "5",
    name: "Spice Noir",
    brand: "Oriental Essence",
    price: 95.99,
    image: "/dark-spice-perfume-bottle-oriental.jpg",
    description: "Warm and sensual with exotic spices and amber",
    notes: ["Cardamom", "Cinnamon", "Amber"],
    volume: "100ml",
    rating: 4.9,
     stock: 21,
  },
  {
    id: "6",
    name: "Citrus Sunrise",
    brand: "Morning Glory",
    price: 68.99,
    image: "/citrus-perfume-bottle-sunrise.jpg",
    description: "Energizing citrus blend to start your day",
    notes: ["Orange", "Grapefruit", "Neroli"],
    volume: "75ml",
    rating: 4.4,
     stock: 2,
  },
  {
    id: "7",
    name: "Velvet Nights",
    brand: "Luxe Fragrances",
    price: 99.99,
    image: "/luxury-dark-perfume-bottle-velvet.jpg",
    description: "Deep and mysterious with oud and leather notes",
    notes: ["Oud", "Leather", "Musk"],
    volume: "100ml",
    rating: 4.9,
     stock: 0,
  },
  {
    id: "8",
    name: "Lavender Dreams",
    brand: "Botanical Bliss",
    price: 62.99,
    image: "/lavender-perfume-bottle-calming.jpg",
    description: "Calming lavender with soft floral undertones",
    notes: ["Lavender", "Chamomile", "Geranium"],
    volume: "75ml",
    rating: 4.6,
     stock: 10,
  },
  {
    id: "9",
    name: "Amber Dusk",
    brand: "Oriental Essence",
    price: 88.5,
    image: "/amber-perfume-bottle-dusk.jpg",
    description: "Golden amber with smoky vanilla and patchouli",
    notes: ["Amber", "Patchouli", "Vanilla"],
    volume: "90ml",
    rating: 4.8,
     stock: 15,
  },
  ؤ,
  {
    id: "11",
    name: "Jasmine Whisper",
    brand: "Botanical Bliss",
    price: 74.99,
    image: "/jasmine-perfume-bottle-white.jpg",
    description: "Delicate jasmine petals with soft musk and vanilla",
    notes: ["Jasmine", "Musk", "Vanilla"],
    volume: "100ml",
    rating: 4.5,
    stock: 5,
  },
  {
    id: "12",
    name: "Noir Intense",
    brand: "Luxe Fragrances",
    price: 105.99,
    image: "/black-perfume-bottle-noir-intense.jpg",
    description: "Bold and powerful with black pepper and tobacco",
    notes: ["Black Pepper", "Tobacco", "Cedarwood"],
    volume: "100ml",
    rating: 4.9,
     stock: 14,
  },
  {
    id: "13",
    name: "Pure Blossom",
    brand: "Fresh Scents",
    price: 64.99,
    image: "/white-blossom-perfume-bottle.jpg",
    description: "Gentle floral blend with lily and freesia notes",
    notes: ["Lily", "Freesia", "Pear"],
    volume: "75ml",
    rating: 4.4,
     stock: 45,
  },
  {
    id: "14",
    name: "Mystic Oud",
    brand: "Oriental Essence",
    price: 110.0,
    image: "/oud-perfume-bottle-mystic.jpg",
    description: "Rich oriental oud with incense and rose accents",
    notes: ["Oud", "Rose", "Incense"],
    volume: "100ml",
    rating: 4.9,
    stock: 5,
  },
  {
    id: "15",
    name: "Vanilla Sky",
    brand: "Morning Glory",
    price: 71.99,
    image: "/vanilla-sky-perfume-bottle.jpg",
    description: "Sweet and creamy vanilla wrapped in soft musk",
    notes: ["Vanilla", "Musk", "Coconut"],
    volume: "90ml",
    rating: 4.6,
     stock: 12,
  },
  {
    id: "16",
    name: "Cedar Whisper",
    brand: "Nature’s Touch",
    price: 78.99,
    image: "/cedar-wood-perfume-bottle.jpg",
    description: "Earthy and grounding blend of cedarwood and vetiver",
    notes: ["Cedarwood", "Vetiver", "Amber"],
    volume: "100ml",
    rating: 4.5,
     stock: 11,
  },
  {
    id: "17",
    name: "Crimson Bloom",
    brand: "Botanical Bliss",
    price: 85.0,
    image: "/crimson-floral-perfume-bottle.jpg",
    description: "Vibrant floral bouquet with pomegranate and rose",
    notes: ["Pomegranate", "Rose", "Peony"],
    volume: "100ml",
    rating: 4.7,
     stock: 10,
  },
  {
    id: "18",
    name: "Silver Rain",
    brand: "Fresh Scents",
    price: 69.99,
    image: "/silver-rain-perfume-bottle.jpg",
    description: "Clean and airy with citrus and white musk notes",
    notes: ["Lime", "Aqua", "White Musk"],
    volume: "75ml",
    rating: 4.4,
     stock: 15,
  },
  {
    id: "19",
    name: "Arabian Nights",
    brand: "Oriental Essence",
    price: 120.0,
    image: "/arabian-nights-perfume-bottle.jpg",
    description: "Exotic blend of oud, saffron, and amber inspired by the Middle East",
    notes: ["Oud", "Saffron", "Amber"],
    volume: "100ml",
    rating: 5.0,
     stock: 0,
  },
  {
    id: "20",
    name: "Peach Blossom",
    brand: "Morning Glory",
    price: 67.99,
    image: "/peach-blossom-perfume-bottle.jpg",
    description: "Sweet fruity fragrance with peach and jasmine notes",
    notes: ["Peach", "Jasmine", "Vanilla"],
    volume: "75ml",
    rating: 4.6,
     stock: 0,
  },
];
